# Generated by Django 5.0.4 on 2024-04-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='os',
            old_name='atributo_1',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='os',
            name='atributo_2',
        ),
    ]
